name: default

on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  tagger:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagger.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          commit-ish: 'HEAD'
          abbrev: false

      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
  
  
  docker:
    runs-on: ubuntu-latest
    needs: [build, tagger]
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gitu/dashboard:${{needs.tagger.outputs.tag}}
          build-args: VERSION=${{needs.tagger.outputs.tag}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
